package com.decent.audio;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import android.content.Context;
import android.content.res.AssetManager;

import androidx.test.ext.junit.runners.AndroidJUnit4;
import androidx.test.platform.app.InstrumentationRegistry;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.RandomAccessFile;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.charset.StandardCharsets;

/**
 * Container provenance is stripped, always.
 *
 * <p>The harm this pins is not hypothetical. The pipeline's sources are
 * MP4-wrapped audio from a streaming platform, and an MP4 carries
 * {@code major_brand}, {@code minor_version}, {@code compatible_brands} and
 * {@code encoder} at container level. Copied into a FLAC they become Vorbis
 * comments and stay in the user's library forever — reference files produced
 * before this rule existed carry exactly {@code major_brand=isom},
 * {@code compatible_brands=isomiso2mp41} and {@code encoder=Lavf61.7.103}, and
 * one Dolby Atmos track downmixed to plain 5.1 carries
 * {@code compatible_brands=mp42dby1}, i.e. a text tag claiming Dolby about
 * audio that is no longer Dolby.
 *
 * <p>The fixture {@code flac_in_mp4.m4a} is the real thing rather than a
 * synthetic case: it was written by ffmpeg's own CLI and therefore carries all
 * four container tags plus stream-level {@code handler_name} / {@code language}
 * — {@link #assertSourceIsWorthTesting()} refuses to let the rest of this class
 * pass if that ever stops being true.
 *
 * <p>Assertions are byte scans of the output, which is what the sibling tests
 * do and what suits the question: a tag is exactly a string in the file, and
 * this build's {@code probe()} deliberately does not read tags back.
 */
@RunWith(AndroidJUnit4.class)
public class FlowyFfmpegMetadataTest {

    /** Tags of the fixture's MP4 container, none of which may reach an output. */
    private static final String[] SOURCE_PROVENANCE = {
            "major_brand", "minor_version", "compatible_brands", "isomiso2mp41",
    };

    private static final String TITLE = "Flowy paw copy :3";
    private static final String ARTIST = "Flowy OwO";
    /** Written into a source by this test, so it can only be there by inheritance. */
    private static final String SOURCE_ONLY = "SHOULD_NOT_SURVIVE";

    private static final int SAMPLE_RATE = 44100;
    private static final int CHANNELS = 2;

    private File dir;

    @Before
    public void setUp() {
        Context context = InstrumentationRegistry.getInstrumentation().getTargetContext();
        dir = new File(context.getCacheDir(), "flowy-ffmpeg-metadata");
        deleteRecursively(dir);
        assertTrue(dir.mkdirs());
    }

    /**
     * The control for every other test here: the fixture must actually have
     * provenance to leak. Without it, a fixture regenerated by some future
     * ffmpeg that stopped writing those tags would turn all of this green while
     * proving nothing.
     *
     * <p>Only the <em>values</em> are asserted here, because in an MP4 that is
     * all there is: the brands live in the {@code ftyp} box as four-character
     * runs and the key names {@code major_brand} / {@code compatible_brands}
     * exist nowhere in the file — the demuxer invents them when it reads the
     * box. That the demuxer really does hand them to us as tags is what
     * {@link #inheritingModeStillInheritsTheContainersTags()} proves, and it is
     * the other half of this control.
     */
    @Test
    public void theFixtureHasProvenanceToLeak() throws IOException {
        File src = asset("flac_in_mp4.m4a");
        assertTrue("the fixture's ftyp brands are gone — it cannot prove anything"
                + " about stripping", contains(src, "isomiso2mp41"));
        assertTrue("the fixture no longer carries an encoder stamp", contains(src, "Lavf62"));
    }

    // ── The three operations, in the default (stripping) mode ────────────

    @Test
    public void encodeFlacCarriesTheCallersTagsAndNoneOfTheSources() throws IOException {
        File out = convert(Operation.ENCODE_FLAC, asset("flac_in_mp4.m4a"),
                "flac-default.flac", FlowyFfmpeg.STRIP_SOURCE_METADATA);

        assertCallersTagsSurvived(out);
        assertNoSourceProvenance(out);
        // A FLAC has no structural "Lavf" anywhere, so this catches both the
        // inherited encoder tag and libavformat's own stamp in one needle.
        assertFalse("libavformat signed the FLAC", contains(out, "Lavf"));
    }

    @Test
    public void encodeMp3CarriesTheCallersTagsAndNoneOfTheSources() throws IOException {
        File out = convert(Operation.ENCODE_MP3, asset("flac_in_mp4.m4a"),
                "mp3-default.mp3", FlowyFfmpeg.STRIP_SOURCE_METADATA);

        assertCallersTagsSurvived(out);
        assertNoSourceProvenance(out);
        // ID3v2 frame IDs, so these are version-independent needles: TSSE is
        // where the encoder tag would land, TXXX is where every container tag
        // with no frame of its own would.
        assertFalse("an encoder frame (TSSE) was written", contains(out, "TSSE"));
        assertFalse("a container tag rode along as TXXX", contains(out, "TXXX"));
        // Deliberately NOT asserted: the Xing header's fixed 9-byte encoder
        // field, which reads "Lavf" whatever we do (mp3enc.c:257). It is
        // bitstream structure — readers key gapless delay/padding detection off
        // it — not a metadata tag.
    }

    @Test
    public void remuxCarriesTheCallersTagsAndNoneOfTheSources() throws IOException {
        File out = convert(Operation.REMUX_FLAC, asset("flac_in_mp4.m4a"),
                "remux-default.flac", FlowyFfmpeg.STRIP_SOURCE_METADATA);

        assertCallersTagsSurvived(out);
        assertNoSourceProvenance(out);
        assertFalse("libavformat signed the FLAC", contains(out, "Lavf"));
    }

    /**
     * The MP4 destination separately, because it is the one container that
     * would otherwise get a {@code ©too} atom of libavformat's own making
     * (movenc.c:4764) rather than an inherited tag.
     *
     * <p>Brands are deliberately NOT asserted on an MP4 output, and the first
     * version of this test was wrong to: movenc writes its own {@code ftyp}, so
     * {@code isomiso2mp41} is in the file as structure whatever the source was
     * — and, unlike a Vorbis comment block, {@code ilst} has no frame for a key
     * movenc does not know, so the source's brands could not ride along as text
     * even if they were inherited. The stamp is the only leak an MP4 has.
     */
    @Test
    public void remuxIntoMp4WritesNoEncoderAtom() throws IOException {
        File src = asset("flac_in_mp4.m4a");
        File out = new File(dir, "remux-default.mp4");
        int rc = FlowyFfmpeg.remux(src.getAbsolutePath(), out.getAbsolutePath(), "mp4",
                new String[]{"title", TITLE}, null);
        assertEquals(FlowyFfmpeg.lastError(), FlowyFfmpeg.OK, rc);

        assertTrue("the caller's title did not reach the MP4", contains(out, TITLE));
        assertFalse("movenc stamped the file", contains(out, "Lavf"));
    }

    // ── The inheriting mode is not decorative ───────────────────────────

    @Test
    public void inheritingModeStillInheritsTheContainersTags() throws IOException {
        File src = asset("flac_in_mp4.m4a");
        for (Operation op : new Operation[]{Operation.ENCODE_FLAC, Operation.REMUX_FLAC}) {
            File out = convert(op, src, op + "-inherited.flac",
                    FlowyFfmpeg.INHERIT_SOURCE_METADATA);

            assertCallersTagsSurvived(out);
            for (String tag : SOURCE_PROVENANCE) {
                assertTrue(op + " asked to inherit and did not carry " + tag,
                        contains(out, tag));
            }
            // Inheriting the source's tags is one thing; wearing libavformat's
            // signature is another. Suppressing the stamp is unconditional, so
            // even here the source's encoder=Lavf62.… does not survive: the
            // muxer deletes the key under AVFMT_FLAG_BITEXACT (mux.c:355).
            assertFalse(op + " kept an encoder stamp", contains(out, "Lavf"));
        }
    }

    /**
     * The "empty value removes a key" semantic, which is meaningful only when
     * something was inherited for it to remove.
     */
    @Test
    public void anEmptyValueRemovesAnInheritedKey() throws IOException {
        File src = asset("flac_in_mp4.m4a");
        File out = new File(dir, "inherited-minus-one.flac");
        int rc = FlowyFfmpeg.encodeFlac(src.getAbsolutePath(), out.getAbsolutePath(), 16,
                new String[]{"title", TITLE, "major_brand", ""},
                null, FlowyFfmpeg.INHERIT_SOURCE_METADATA);
        assertEquals(FlowyFfmpeg.lastError(), FlowyFfmpeg.OK, rc);

        assertTrue(contains(out, TITLE));
        assertFalse("an empty value did not remove the inherited key",
                contains(out, "major_brand"));
        assertTrue("the removal took the other inherited tags with it",
                contains(out, "compatible_brands"));
    }

    // ── A source this test wrote itself ─────────────────────────────────

    /**
     * The fixture proves the MP4 case; this proves the general one, on a source
     * whose distinctive tag exists nowhere else in the world. It also closes the
     * loop on the parameter: the same source, the same operation, both modes.
     */
    @Test
    public void aTagOnlyTheSourceHasDoesNotCrossOverUnlessAsked() throws IOException {
        File wav = new File(dir, "tone.wav");
        writeToneWav(wav, 2000);

        // Built with the library itself: the caller's tags always land, whatever
        // the mode, so this needs no inheriting to carry SOURCE_ONLY.
        File tagged = new File(dir, "tagged.flac");
        assertEquals(FlowyFfmpeg.lastError(), FlowyFfmpeg.OK,
                FlowyFfmpeg.encodeFlac(wav.getAbsolutePath(), tagged.getAbsolutePath(), 16,
                        new String[]{"comment", SOURCE_ONLY, "title", "source title"}, null));
        assertTrue("the source was not tagged, so the rest proves nothing",
                contains(tagged, SOURCE_ONLY));

        for (Operation op : Operation.values()) {
            File stripped = convert(op, tagged, op + "-stripped" + op.extension, false);
            assertCallersTagsSurvived(stripped);
            assertFalse(op + " carried the source's comment across",
                    contains(stripped, SOURCE_ONLY));

            File inherited = convert(op, tagged, op + "-inherited" + op.extension, true);
            assertCallersTagsSurvived(inherited);
            assertTrue(op + " was asked to inherit and did not",
                    contains(inherited, SOURCE_ONLY));
        }
    }

    // ── Helpers ─────────────────────────────────────────────────────────

    /**
     * The three published operations, plus the stream copy's other destination
     * — an MP4, whose {@code ©cmt} atom is where an inherited comment would
     * land. Every one of them takes a FLAC source, which is what the round-trip
     * test feeds them.
     */
    private enum Operation {
        REMUX_FLAC("flac", ".flac"),
        REMUX_MP4("mp4", ".m4a"),
        ENCODE_FLAC(null, ".flac"),
        ENCODE_MP3(null, ".mp3");

        final String muxer;
        final String extension;

        Operation(String muxer, String extension) {
            this.muxer = muxer;
            this.extension = extension;
        }
    }

    /** Runs one operation with the caller's tags and the given metadata policy. */
    private File convert(Operation op, File src, String name, boolean inherit) {
        File out = new File(dir, name);
        String[] metadata = {"title", TITLE, "artist", ARTIST};
        int rc;
        switch (op) {
            case REMUX_FLAC:
            case REMUX_MP4:
                rc = FlowyFfmpeg.remux(src.getAbsolutePath(), out.getAbsolutePath(), op.muxer,
                        metadata, null, inherit);
                break;
            case ENCODE_FLAC:
                rc = FlowyFfmpeg.encodeFlac(src.getAbsolutePath(), out.getAbsolutePath(), 16,
                        metadata, null, inherit);
                break;
            case ENCODE_MP3:
                rc = FlowyFfmpeg.encodeMp3(src.getAbsolutePath(), out.getAbsolutePath(), 320,
                        metadata, null, inherit);
                break;
            default:
                throw new AssertionError(op);
        }
        assertEquals(op + ": " + FlowyFfmpeg.lastError(), FlowyFfmpeg.OK, rc);
        assertTrue(op + " produced nothing", out.length() > 0);
        return out;
    }

    private static void assertCallersTagsSurvived(File out) {
        assertTrue("the caller's title is missing from " + out.getName(),
                contains(out, TITLE));
        assertTrue("the caller's artist is missing from " + out.getName(),
                contains(out, ARTIST));
    }

    private static void assertNoSourceProvenance(File out) {
        for (String tag : SOURCE_PROVENANCE) {
            assertFalse("the source's " + tag + " survived into " + out.getName(),
                    contains(out, tag));
        }
    }

    private File asset(String name) throws IOException {
        AssetManager assets =
                InstrumentationRegistry.getInstrumentation().getContext().getAssets();
        File file = new File(dir, name);
        try (InputStream in = assets.open(name);
             FileOutputStream out = new FileOutputStream(file)) {
            byte[] buf = new byte[16384];
            int n;
            while ((n = in.read(buf)) > 0) out.write(buf, 0, n);
        }
        assertTrue(name + " did not land in the test APK", file.length() > 0);
        return file;
    }

    /** The same canonical 44-byte-header WAV the sibling tests write. */
    private static void writeToneWav(File file, int durationMs) throws IOException {
        int frames = (int) ((long) SAMPLE_RATE * durationMs / 1000);
        int dataBytes = frames * CHANNELS * 2;
        ByteBuffer buf = ByteBuffer.allocate(44 + dataBytes).order(ByteOrder.LITTLE_ENDIAN);
        buf.put("RIFF".getBytes(StandardCharsets.US_ASCII));
        buf.putInt(36 + dataBytes);
        buf.put("WAVE".getBytes(StandardCharsets.US_ASCII));
        buf.put("fmt ".getBytes(StandardCharsets.US_ASCII));
        buf.putInt(16);
        buf.putShort((short) 1);
        buf.putShort((short) CHANNELS);
        buf.putInt(SAMPLE_RATE);
        buf.putInt(SAMPLE_RATE * CHANNELS * 2);
        buf.putShort((short) (CHANNELS * 2));
        buf.putShort((short) 16);
        buf.put("data".getBytes(StandardCharsets.US_ASCII));
        buf.putInt(dataBytes);
        for (int i = 0; i < frames; i++) {
            double t = (double) i / SAMPLE_RATE;
            buf.putShort((short) (Math.sin(2 * Math.PI * 440 * t) * 12000));
            buf.putShort((short) (Math.sin(2 * Math.PI * 660 * t) * 12000));
        }
        try (FileOutputStream out = new FileOutputStream(file)) {
            out.write(buf.array());
        }
    }

    private static boolean contains(File file, String needle) {
        byte[] pattern = needle.getBytes(StandardCharsets.UTF_8);
        try (RandomAccessFile raf = new RandomAccessFile(file, "r")) {
            byte[] all = new byte[(int) raf.length()];
            raf.readFully(all);
            outer:
            for (int i = 0; i + pattern.length <= all.length; i++) {
                for (int j = 0; j < pattern.length; j++) {
                    if (all[i + j] != pattern[j]) continue outer;
                }
                return true;
            }
        } catch (IOException e) {
            return false;
        }
        return false;
    }

    private static void deleteRecursively(File file) {
        File[] children = file.listFiles();
        if (children != null) {
            for (File child : children) deleteRecursively(child);
        }
        file.delete();
    }
}
