/*
 * Copyright (C) 2016 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef SEEK_TABLE_SANITIZE_H_
#define SEEK_TABLE_SANITIZE_H_

#include <stdint.h>

#include <vector>

// Sanitizes a FLAC SEEKTABLE before the parser trusts it for seeking.
//
// The trap this pins (seen in a field file): a seek table generated by
// scanning the stream for frame sync codes can contain FALSE-SYNC entries —
// a byte pattern inside compressed audio that looks like a frame header and
// passes the 8-bit header CRC (1/256 per candidate, so a large file EXPECTS
// a few). The observed entry was sample_number=7, frame_samples=1024 sitting
// between valid neighbors at samples 5852160 and 5939712. The seek resolver
// walks the table from the END looking for the last entry <= target, so that
// single entry captured EVERY backward seek below its valid successor and
// teleported playback to its byte offset (~2 minutes in) — while forward
// seeks, served sample-exactly from the already-buffered region without
// consulting the table, kept working. The FLAC spec requires seek points to
// be sorted by strictly ascending sample number, so dropping violators only
// rejects tables that are already out of spec.
//
// Rules, applied in order per entry:
//  1. Placeholder entries (sample_number all-ones) are skipped silently —
//     legal per spec, not corruption.
//  2. An entry with sample_number >= totalSamples (when known) is dropped —
//     no real frame starts there, and keeping a huge garbage value would
//     make the monotonicity rule below reject every valid entry after it.
//  3. sample_number AND stream_offset must be strictly increasing over the
//     kept sequence; an entry that breaks either is dropped. A false-sync
//     intruder sits between valid neighbors, so keep-first drops exactly
//     the intruder.
//
// Templated on the point type so the logic is testable without libFLAC
// headers; instantiated with FLAC__StreamMetadata_SeekPoint in production.
// Returns the number of dropped (non-placeholder) entries.
template <typename SeekPoint>
size_t sanitizeSeekPoints(const SeekPoint* points, unsigned numPoints,
                          uint64_t totalSamples, std::vector<SeekPoint>* out) {
  const uint64_t kPlaceholder = 0xFFFFFFFFFFFFFFFFULL;
  out->clear();
  out->reserve(numPoints);
  size_t dropped = 0;
  for (unsigned i = 0; i < numPoints; i++) {
    const SeekPoint& p = points[i];
    if ((uint64_t)p.sample_number == kPlaceholder) {
      continue;
    }
    if (totalSamples != 0 && (uint64_t)p.sample_number >= totalSamples) {
      dropped++;
      continue;
    }
    if (!out->empty()) {
      const SeekPoint& prev = out->back();
      if ((uint64_t)p.sample_number <= (uint64_t)prev.sample_number ||
          (uint64_t)p.stream_offset <= (uint64_t)prev.stream_offset) {
        dropped++;
        continue;
      }
    }
    out->push_back(p);
  }
  return dropped;
}

#endif  // SEEK_TABLE_SANITIZE_H_
