#!/bin/busybox sh
/bin/busybox --install -s /bin
export PATH=/bin:/sbin:/usr/bin:/usr/sbin
mount -t devtmpfs devtmpfs /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys
modprobe xhci-pci
sleep 2
/harness
result=$?
echo "HARNESS_EXIT=$result"
poweroff -f
